hotel_management/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.reservation_detail, name='reservation_detail'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('laundry_basket_add/', views.laundry_basket_add, name='laundry_basket_add'),
    path('fb_meal_basket_add/', views.fb_meal_basket_add, name='fb_meal_basket_add'),
    # path('delete/', views.basket_delete, name='basket_delete'),
    # path('update/', views.basket_update, name='basket_update'),
]

hotel_management/booking/urls.py
from django.urls import path

from . import views

app_name = 'booking'

urlpatterns = [
    path('visa_payment/', views.visa_payment, name='visa_payment'),
    path('search_booking_room/', views.search_booking_room, name='search_booking_room'),
    path('update_booking_db/', views.update_booking_db, name='update_booking_db'),
    path('calculate_promo/', views.calculate_promo, name='calculate_promo'),
    path('save_promo_to_session/', views.save_promo_to_session, name='save_promo_to_session'),
    path('checkout_page/', views.checkout_page, name='checkout_page'),
    path('booking_invoice/<str:pk>/', views.booking_invoice, name='booking_invoice'),
    
]

hotel_management/hotel_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('account/', include('human_resource.urls', namespace='human_resource')),
    path('service/', include('service.urls', namespace='service')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel_management/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('room_all/', views.room_all, name="room_all"),
    path('<slug:slug>', views.room_detail, name="room_detail"),

    # path('reservation_detail/', views.reservation_detail, name="reservation_detail"),
    path('service/', views.service, name="service"),
    path('service/service_meal', views.service_meal, name="service_meal"),
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('team/', views.team, name="team"),
    # path('booking/', views.booking, name="booking"),
    path('contact/', views.contact, name="contact"),
    path('testimonial/', views.testimonial, name="testimonial"),
]

hotel_management/booking/views.py
from django.shortcuts import render
from django.db.models import Sum
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers import serialize
import json
# from django.utils.decorators import method_decorator


from .handle_decimal import DecimalEncoder

from .models import BookingInfor, TranInfor, Country, RentalInfor, PaymentMethod, Promo, PaymentTranInfor
from basket.basket import Basket
from human_resource.models import Guest
from store.models import Room, RoomType
from service.models import MealCode, MealChargeTranInfor, FBTranInfor, LaundryTranInfor

from datetime import datetime, timedelta
from decimal import Decimal

def booking_invoice(request, pk):
    today_str = str(datetime.now().date())
    booking_infor = get_object_or_404(BookingInfor, id=pk)
    
    tran_infors = TranInfor.objects.filter(booking_id= booking_infor)
    rental_infors = RentalInfor.objects.filter(tran_id__in=tran_infors)
    # tiền ăn uống tại khách sạn
    fb_trans = FBTranInfor.objects.filter(rental_id__in=rental_infors)
    try:
        total_meal_cost = fb_trans.aggregate(total_cost=Sum('total_amount_paid'))['fb_total_cost']
    except:
        total_meal_cost = 0

    # giặt là
    laundry_trans = LaundryTranInfor.objects.filter(rental_id__in=rental_infors)
    try:
        total_laudry_cost = laundry_trans.aggregate(total_cost=Sum('total_amount_paid'))['total_laudry_cost']
    except:
        total_laudry_cost = 0

    # tiền phòng và dịch vụ đặt qua website đã có khuyến mãi
    payment_for_total = round(float(booking_infor.payment_for_total), 2)
    print("####################")
    print(total_meal_cost)
    print(total_laudry_cost)
    print(payment_for_total)
    print("####################")
    # tien dat coc
    payment_deposit = round(payment_for_total/2, 2)
    # tong so tien cuoi cung
    payment_final = round(payment_for_total + total_laudry_cost + total_meal_cost, 2)
    # thue
    tax = round(payment_final/11, 2)
    # so tien con phai tra
    payment_remain = payment_final - payment_deposit


    return render(request, 'checkout/booking_invoice.html', {'booking_infor':booking_infor, 'today_str':today_str, 'payment_for_total':payment_for_total, 'total_meal_cost':total_meal_cost, 'total_laudry_cost':total_laudry_cost, 'payment_deposit':payment_deposit, 'tax':tax, 'payment_final':payment_final, 'payment_remain':payment_remain})

def checkout_page(request):
    today_str = str(datetime.now().date())
    today = datetime.strptime(today_str, "%Y-%m-%d")

    booking_infors = BookingInfor.objects.filter(departure_date=today)
    # tran_infors = TranInfor.objects.filter(booking_id__in =booking_infors)
    # tran_infors = TranInfor.objects.all()
    # tran_infor = TranInfor()
    return render(request, 'checkout/checkout.html', {'booking_infors':booking_infors, 'today_str':today_str})

def save_promo_to_session(request):
    if request.POST.get('action') == 'post':
        total_for_payment = request.POST.get('value')
    request.session['total_for_payment'] = total_for_payment
    response = JsonResponse({'name': 'Phạm Văn Thái'});
    return response

def visa_payment(request):
    total_for_payment = request.session['total_for_payment']
    if 'checkin' in request.session and 'checkout' in request.session:
        arrival_date_str = request.session['checkin']
        departure_date_str = request.session['checkout']
        arrival_date = datetime.strptime(arrival_date_str, "%Y-%m-%d")
        departure_date = datetime.strptime(departure_date_str, "%Y-%m-%d")
        days_difference = int((departure_date - arrival_date).days)
        total_for_payment_entire_trip = round(float(total_for_payment)*days_difference, 2)
    else:
        total_for_payment_entire_trip = total_for_payment
    countries = Country.objects.all()
    payments = PaymentMethod.objects.all()
    
    return render(request, 'payment/visa_payment.html', {'countries':countries, 'payments':payments, 'total_for_payment':total_for_payment, 'total_for_payment_entire_trip':total_for_payment_entire_trip, 'arrival_date_str':arrival_date_str, 'departure_date_str':departure_date_str})

def search_booking_room(request):
    # booking_data = BookingData(request)
    if request.POST.get('action') == 'post':
        checkin_date_str = str(request.POST.get('checkin_date'))
        checkout_date_str = str(request.POST.get('checkout_date'))
        adultqty_search = str(request.POST.get('adultqty_search'))
        roomtype_search = str(request.POST.get('roomtype_search'))
        print(checkin_date_str, checkout_date_str)

        request.session['checkin'] = checkin_date_str
        request.session['checkout'] = checkout_date_str

        request.session.modified = True
    print(request.session['checkin'])
    print(request.session['checkout'])

        # booking_data.add(checkin_date_str=checkin_date_str, checkout_date_str=checkout_date_str)
        # print(booking_data.booking_data)

     # convert string dates to date objects
    checkin_date = datetime.strptime(checkin_date_str, '%Y-%m-%d')
    checkout_date = datetime.strptime(checkout_date_str, '%Y-%m-%d')
    print(checkin_date, checkout_date)
    print(adultqty_search, roomtype_search)



    # query for RentalInfor in the specified date range
    rentals = RentalInfor.objects.filter(
        rental_date__range=(checkin_date, checkout_date)
    )

    # Xây dựng Q objects cho các điều kiện tìm kiếm
    if roomtype_search == 'Loại phòng':
        roomtype_search = ''
    # if adultqty_search == 'Số người mỗi phòng':
    #     adultqty_search = ''    
    conditions = Q()

    if roomtype_search:
        conditions &= Q(name=roomtype_search)

    # if adultqty_search:
    #     conditions &= Q(bed_adult=adultqty_search)

    # Lấy room_types với các điều kiện đã xây dựng
    room_types = RoomType.objects.filter(conditions)

    # extract room_ids
    room_ids = rentals.values_list('room_id', flat=True).distinct()

    # optionally, get room objects if needed
    rooms_query_sub = Room.rooms.exclude(id__in=room_ids, room_type_id__in=room_types)
    rooms_query = rooms_query_sub.filter(room_type_id__in=room_types)

    # 

    # Render the bookings to an HTML template
    rendered_template = render(request, 'room/room_all_search.html', {'rooms_query': rooms_query}).content.decode('utf-8')

    # # Return the rendered HTML as part of the JSON response
    response = JsonResponse({'html': rendered_template})
    return response

def update_booking_db(request):
    basket = Basket(request)
    
    # lấy thông tin từ form thanh toán
    if request.POST.get('action') == 'post':
        firstName = request.POST.get('firstName')
        lastName = request.POST.get('lastName')
        email = request.POST.get('email')
        address = request.POST.get('address')
        phonenumber = request.POST.get('phonenumber')
        country = request.POST.get('country')
        # state = int(request.POST.get('state'))
        zipcode = request.POST.get('zip')
        paymentMethod = request.POST.get('paymentMethod')
        totalForPaymentPerDay = request.POST.get('totalForPayment')
        # cardName = int(request.POST.get('cardName'))
        # cardNumber = int(request.POST.get('cardNumber'))

    # lấy thông tin từ basket    

    guest = Guest.objects.create(
                first_name=firstName,
                last_name=lastName,
            )
    
    # arrival_date_str = '2024-06-06'
    arrival_date_str = request.session['checkin']
    arrival_date = datetime.strptime(arrival_date_str, "%Y-%m-%d")

    # departure_date_str = '2024-06-07'
    departure_date_str = request.session['checkout']
    departure_date = datetime.strptime(departure_date_str, "%Y-%m-%d")
    # tính số ngày giữa hai ngày
    days_difference = int((departure_date - arrival_date).days)
    # so tien can thanh toan trong n ngay
    totalForPayment = float(totalForPaymentPerDay)*days_difference

    print(arrival_date_str, departure_date_str, days_difference, totalForPayment)

    # Tạo danh sách các ngày
    date_list = []
    current_date = arrival_date
    while current_date < departure_date:
        date_list.append(current_date)
        current_date += timedelta(days=1)
    
    country_obj = Country.objects.get(country_code=country)

    adult_qty = basket.get_adult_qty()
    child_qty = basket.get_child_qty()

    booking_infor = BookingInfor.objects.create(
        first_name = firstName,
        last_name = lastName,
        email = email,
        phone_number = phonenumber,
        address = address,
        zipcode = zipcode,
        country_link = country_obj,
        arrival_date = arrival_date,
        departure_date = departure_date,
        adults = adult_qty,
        childs = child_qty,
        nights = days_difference,
        guest_id = guest,
        payment_for_total = totalForPayment
    )

    # payment_method = PaymentMethod.objects.get(name=paymentMethod)

    payment_infor = PaymentTranInfor.objects.create(
        booking_infor = booking_infor,
        payment_method = paymentMethod,
        amount_paid = totalForPayment,
        current_amount_paid = totalForPayment
    )

    for key, value in basket.basket.items():
        room_id = str(key)
        adult_qty_each_room = value['adult_qty']
        child_qty_each_room = value['child_qty']

        # thiếu nhân với số nights, nights được tính bằng phép trừ ngày departure cho arrival
        # tạm thời tran_infor sẽ sử dụng total_rent_each_day chưa đúng, total_rent_each_tran mới đúng
        total_rent_each_day = int(value['price'])
        total_rent_tax_each_day = int(value['price'])/10
        total_rent_overall_each_day = float(total_rent_each_day + total_rent_tax_each_day)

        total_rent = int(value['price']) * days_difference

hotel_management/templates/about.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Room All{% endblock %}
{% block content %}

<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 align-items-center">
            <div class="col-lg-6">
                <h6 class="section-title text-start text-primary text-uppercase">About Us</h6>
                <h1 class="mb-4">Welcome to <span class="text-primary text-uppercase">Hotelier</span></h1>
                <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                <div class="row g-3 pb-4">
                    <div class="col-sm-4 wow fadeIn" data-wow-delay="0.1s">
                        <div class="border rounded p-1">
                            <div class="border rounded text-center p-4">
                                <i class="fa fa-hotel fa-2x text-primary mb-2"></i>
                                <h2 class="mb-1" data-toggle="counter-up">1234</h2>
                                <p class="mb-0">Rooms</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 wow fadeIn" data-wow-delay="0.3s">
                        <div class="border rounded p-1">
                            <div class="border rounded text-center p-4">
                                <i class="fa fa-users-cog fa-2x text-primary mb-2"></i>
                                <h2 class="mb-1" data-toggle="counter-up">1234</h2>
                                <p class="mb-0">Staffs</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 wow fadeIn" data-wow-delay="0.5s">
                        <div class="border rounded p-1">
                            <div class="border rounded text-center p-4">
                                <i class="fa fa-users fa-2x text-primary mb-2"></i>
                                <h2 class="mb-1" data-toggle="counter-up">1234</h2>
                                <p class="mb-0">Clients</p>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="btn btn-primary py-3 px-5 mt-2" href="{% url 'store:room_all' %}">Explore More</a>
            </div>
            <div class="col-lg-6">
                <div class="row g-3">
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.1s" src="{% static 'img/about-1.jpg' %}" style="margin-top: 25%;">
                    </div>
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.3s" src="{% static 'img/about-2.jpg' %}">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-50 wow zoomIn" data-wow-delay="0.5s" src="{% static 'img/about-3.jpg' %}">
                    </div>
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.7s" src="{% static 'img/about-4.jpg' %}">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

hotel_management/templates/booking-component.html
<div class="container-fluid booking pb-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container">
        <div class="bg-white shadow" style="padding: 35px;">
            <div class="row g-2">
                <div class="col-md-10">
                    <div class="row g-2">

                        <div class="col-md-3">
                            <!-- <div class="date" id="date1" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input"
                                    placeholder="Check in" data-target="#date1"  />
                            </div> -->
                            <input class="form-control" type="date" id="checkin" name="birthday" placeholder="Check in">

                        </div>
                        <div class="col-md-3">
                            <!-- <div class="date" id="date2" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" placeholder="Check out" data-target="#date2" data-toggle="datetimepicker"/>
                            </div> -->
                            <input class="form-control" type="date" id="checkout" name="birthday"
                                placeholder="Check out">
                        </div>
                        <div class="col-md-3">
                            <select class="form-select" id="booking-adult-select">
                                <option selected>Số người mỗi phòng</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <select class="form-select" id="booking-roomtype-select">
                                <option selected>Loại phòng</option>
                                {% for room_type in room_types %}
                                <option value="1"><a href="https://pypi.org/project/pillow/">{{room_type}}</a></option>
                                {% endfor %}
                            </select>
                        </div>

                    </div>
                </div>
                <div class="col-md-2">
                    <button type="button" class="btn btn-primary w-100" id="js-btn-search-room"
                        onclick="myFunction()">Tìm phòng</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function myFunction() {
        $(document).on('click', '#js-btn-search-room', function (e) {
            e.preventDefault();
            var checkin_date = document.getElementById("checkin").value;
            var checkout_date = document.getElementById("checkout").value;
            var adultqty_search =  $('#booking-adult-select option:selected').text();
            var roomtype_search = $('#booking-roomtype-select option:selected').text();
            console.log(checkin_date);
            console.log(checkout_date);
            console.log(roomtype_search);
            console.log(adultqty_search);
            $.ajax({
                type: 'POST',
                url: '{% url "booking:search_booking_room" %}',
                data: {
                    checkin_date: checkin_date,
                    checkout_date: checkout_date,
                    adultqty_search: $('#booking-adult-select option:selected').text(),
                    roomtype_search: $('#booking-roomtype-select option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {
                    if (json && json.html) {
                        document.open();
                        document.write(json.html);
                        document.close();
            }
                },
                error: function (xhr, errmsg, err) { }
            });
        })
    }
</script>

hotel_management/templates/reservation_detail.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Reservation Detail{% endblock %}
{% block content %}

<div class="container-xxl py-5">
    <div class="main">
        <div class="page-title">Thông tin đặt phòng</div>

        <div class="checkout-grid">
            <div class="order-summary">
                {% for item in basket %}
                {% with room=item.room %}
                <div class="cart-item-container room-item">
                    <!-- <div class="delivery-date">
                        Delivery date: Tuesday, June 21
                    </div> -->

                    <div class="cart-item-details-grid">
                        <img class="product-image" src="{{room.image.url}}" height="300" width="300">

                        <div class="cart-item-details">
                            <div class="product-name">
                                <h5>{{room.room_code}}</h5>
                            </div>
                            <div class="product-price">
                                ${{room.price}}
                            </div>
                            <div class="product-quantity">
                                <span>
                                    Số lượng: <span class="quantity-label">{{item.qty}}</span>
                                </span>
                                <button class="update-quantity-link link-primary" style="border: none;background-color: white;">
                                    Sửa
                                </button>
                                <button data-index="{{room.id}}" class="delete-quantity-link link-primary js-delete-room-button" style="border: none;background-color: white;">
                                    Xóa
                                </button>
                            </div>
                                <div class="col"><strong>Meal code - {{item.meal_code}}</strong></div>
                                <div class="col"><small>Đặt qua website được giảm 10%</small></div>
                                <div class="col"><small>Người lớn: {{item.adult_qty}} người - ${{item.adult_meal_cost}}</small></div>
                                <div class="col"><small>Trẻ em: {{item.child_qty}} người - ${{item.child_meal_cost}}</small></div>
                            </div>
                        

                        <!-- <div class="delivery-options">
                            <div class="delivery-options-title">
                                Choose a delivery option:
                            </div>
                            <select class="form-select" aria-label="Default select example">
                                <option selected>Open this select menu</option>
                                <option value="1">One Black and Gray Athletic Cotton Socks - 6 Pairs Black and Gray Athletic Cotton Socks - 6 Pairs</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                              </select>
                        </div> -->
                    </div>
                    
                </div>
                {% endwith %}
                {% endfor %}
            </div>

            <div class="payment-summary">
                <div class="payment-summary-title">
                    Tổng hợp chi phí
                </div>

                <div class="payment-summary-row">
                    <div>Tiền phòng:</div>
                    <div class="payment-summary-money">${{basket.get_cost_before_tax}}</div>
                </div>

                <div class="payment-summary-row">
                    <div>Dịch vụ ăn uống:</div>
                    <div class="payment-summary-money">${{basket.get_total_meal_cost}}</div>
                </div>

                <div class="payment-summary-row subtotal-row">
                    <div>Tổng tiền trước thuế:</div>
                    <div class="payment-summary-money">${{basket.get_total_cost_before_tax}}</div>
                </div>

                <div class="payment-summary-row">
                    <div>Tiền thuế (10%):</div>
                    <div class="payment-summary-money">$ {{basket.get_total_tax}}</div>
                </div>

                <form action="" class="row" id="promo-form">
                    {% csrf_token %}
                    <div class="col">
                        <input type="text" id="fname" name="fname" value="" placeholder="Nhập mã giảm giá..."><br>
                    </div>
                    
                    <input type="submit" value="Áp dụng" class="col-3" style="background-color: orange;border: none;border-radius: 3px;">
                  </form>

                <div class="payment-summary-row total-row">
                    <div>Chi phí 1 ngày:</div>
                    <div class="payment-summary-money">$<span id="total-for-payment">{{basket.get_total_cost_with_tax}}</span></div>
                </div>

                <button class="place-order-button button-primary" onclick="placeOrder()" style="background-color: orange;border: none;border-radius: 3px;">
                    Tiến hành thanh toán
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    // Delete Item
    $(document).on('click', '.js-delete-room-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_delete" %}',
        data: {
          roomid: $(this).data('index'),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          $('.room-item[data-index="' + prodid + '"]').remove();
          document.getElementById("subtotal").innerHTML = json.subtotal;
          document.getElementById("basket-qty").innerHTML = json.qty;
        },
        error: function (xhr, errmsg, err) {}
      });
    })

    // Tính toán khuyến mãi
    function placeOrder() {
    // Truy cập đến URL 'booking:visa_payment'
    window.location.href = '{% url "booking:visa_payment" %}';
    // "window.location.href='{% url 'booking:visa_payment' %}'"
    var total_for_payment = document.getElementById("total-for-payment").innerHTML;
    console.log(total_for_payment)

    // Lưu giá trị "10" vào session
    $.ajax({
        url: '{% url "booking:save_promo_to_session" %}',
        type: 'POST',
        data: {
            value: total_for_payment,
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
        },
        success: function(response) {
            console.log('Value saved in session.');
        },
        error: function(xhr, status, error) {
            console.error('Failed to save value in session: ' + error);
        }
    });
};
    function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        
        const csrftoken = getCookie('csrftoken');

        $(document).ready(function() {
            $('#promo-form').on('submit', function(event) {
                event.preventDefault(); // Ngăn form nộp theo cách truyền thống

                var promoCode = $('#fname').val(); // Lấy giá trị từ input

                console.log(promoCode);

                $.ajax({
                    url: '{% url "booking:calculate_promo" %}',
                    type: 'POST',
                    data: {
                        fname: promoCode
                    },
                    headers: {
                        'X-CSRFToken': csrftoken
                    },
                    success: function(response) {
                        // Xử lý phản hồi từ server (nếu có)
                        // alert('Mã giảm giá đã được gửi: ' + response);
                        console.log(response.total_for_payment);
                        document.getElementById("total-for-payment").innerHTML = response.total_for_payment;

                    },
                    error: function(xhr, status, error) {
                        // Xử lý lỗi (nếu có)
                        console.error('Đã xảy ra lỗi: ' + error);
                    }
                });
            });
        });
</script>

{% endblock %}

hotel_management/templates/testimonial.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Room All{% endblock %}
{% block content %}



{% endblock %}