hotel_management/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.reservation_detail, name='reservation_detail'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('laundry_basket_add/', views.laundry_basket_add, name='laundry_basket_add'),
    path('fb_meal_basket_add/', views.fb_meal_basket_add, name='fb_meal_basket_add'),
    # path('delete/', views.basket_delete, name='basket_delete'),
    # path('update/', views.basket_update, name='basket_update'),
]

hotel_management/hotel_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('account/', include('human_resource.urls', namespace='human_resource')),
    path('service/', include('service.urls', namespace='service')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel_management/service/urls.py
from django.urls import path

from . import views

app_name = 'service'

urlpatterns = [
    path('food_drink_store/', views.food_drink_store, name='food_drink_store'),
    path('food_drink_summary/', views.food_drink_summary, name='food_drink_summary'),
    path('update_laundry_tran_db/', views.update_laundry_tran_db, name='update_laundry_tran_db'),
    path('fb_meal_all/', views.fb_meal_all, name='fb_meal_all'),
    path('fb_meal_summary/', views.fb_meal_summary, name='fb_meal_summary'),
    path('update_fb_tran_db/', views.update_fb_tran_db, name='update_fb_tran_db'),
    
]

hotel_management/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('room_all/', views.room_all, name="room_all"),
    path('<slug:slug>', views.room_detail, name="room_detail"),

    # path('reservation_detail/', views.reservation_detail, name="reservation_detail"),
    path('service/', views.service, name="service"),
    path('service/service_meal', views.service_meal, name="service_meal"),
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('team/', views.team, name="team"),
    # path('booking/', views.booking, name="booking"),
    path('contact/', views.contact, name="contact"),
    path('testimonial/', views.testimonial, name="testimonial"),
]

hotel_management/service/models.py
from django.db import models
from django.urls import reverse

from booking.models import TranInfor, RentalInfor, Charges
from human_resource.models import Guest
from store.models import Room

class MealCode(models.Model):
    meal_code = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    description = models.CharField(max_length=250)
    adult_price = models.DecimalField(max_digits=15,decimal_places=2, default=0)
    child_price = models.DecimalField(max_digits=15,decimal_places=2, default=0)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='front-desk')
    modified_by = models.CharField(max_length=255, default='front-desk')
    is_deleted = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Meals'
        ordering = ('-created_date',)

    def __str__(self):
        return self.meal_code

class MealChargeTranInfor(models.Model):
    tran_infor = models.ForeignKey(TranInfor, on_delete=models.CASCADE)
    rental_infor = models.ForeignKey(RentalInfor, on_delete=models.CASCADE)
    meal_code = models.ForeignKey(MealCode, on_delete=models.SET_NULL, null=True)
    quantity_adult = models.IntegerField(default=1)
    quantity_child = models.IntegerField(default=1)
    is_booked_before = models.BooleanField(default=False) # Meal plan da duoc dat tu truoc hay chua
    charge = models.ForeignKey(Charges, on_delete=models.SET_NULL, null=True)
    # guest = models.ForeignKey(Guest, on_delete=models.SET_NULL, null=True)
    # is_adult = models.BooleanField(default=True)

    amount_paid = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    rent_tax = models.DecimalField(max_digits=15,decimal_places=2, default=0)
    rent_total = models.DecimalField(max_digits=15,decimal_places=2, default=0)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='front-desk')
    modified_by = models.CharField(max_length=255, default='front-desk')
    is_deleted = models.BooleanField(default=False)

class LaundryService(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='front-desk')
    modified_by = models.CharField(max_length=255, default='front-desk')
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class ClotheCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='front-desk')
    modified_by = models.CharField(max_length=255, default='front-desk')
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class LaundryItemServicePrice(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    # slug = models.SlugField(max_length=255)
    description = models.CharField(max_length=255)
    laundry_service_id = models.ForeignKey(LaundryService, on_delete=models.SET_NULL, null=True)
    clothe_category_id = models.ForeignKey(ClotheCategory, on_delete=models.SET_NULL, null=True)
    cost = models.FloatField()

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='front-desk')
    modified_by = models.CharField(max_length=255, default='front-desk')
    is_deleted = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'LaundryItemServicePrices'
        ordering = ('-created_date',)
    
    def __str__(self):
        return self.name
    
class LaundryExtraService(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    cost = models.FloatField()

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='front-desk')
    modified_by = models.CharField(max_length=255, default='front-desk')
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
class LaundryTranInfor(models.Model):
    # link voi tran va rental co day du thong tin cua khach roi
    # tran_id = models.ForeignKey(TranInfor, on_delete=models.CASCADE, null=True, blank=True)
    rental_id = models.ForeignKey(RentalInfor, on_delete=models.CASCADE)
    room_id = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    # khong can thiet lam, do don vi tinh bao gom ca kg va cai
    total_items = models.IntegerField(blank=True, null=True)
    laundry_extra_service_id = models.ForeignKey(LaundryExtraService, blank=True, null=True, on_delete=models.SET_NULL)
    amount_paid = models.FloatField()
    amount_tax = models.FloatField()
    total_amount_paid = models.FloatField()
    guest_laundry_time = models.DateTimeField(blank=True, null=True)
    delivery_time = models.DateTimeField(blank=True, null=True)
    description = models.CharField(max_length=255)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='front-desk')
    modified_by = models.CharField(max_length=255, default='front-desk')
    is_deleted = models.BooleanField(default=False)

    # def __str__(self):
    #     return self.name

class FBType(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='admin')
    modified_by = models.CharField(max_length=255, default='admin')
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
class FBMeal(models.Model):
    name = models.CharField(max_length=255)
    fb_type = models.ForeignKey(FBType, models.CASCADE)
    description = models.CharField(max_length=255)
    cost = models.FloatField()
    image = models.ImageField(upload_to='images/', default='images/default.png')

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='admin')
    modified_by = models.CharField(max_length=255, default='admin')
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class FBTranInfor(models.Model):
    # link voi tran va rental co day du thong tin cua khach roi
    # tran_id = models.ForeignKey(TranInfor, on_delete=models.CASCADE, null=True, blank=True)
    rental_id = models.ForeignKey(RentalInfor, on_delete=models.CASCADE)
    room_id = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    # khong can thiet lam, do don vi tinh bao gom ca kg va cai
    amount_paid = models.FloatField()
    amount_tax = models.FloatField()
    total_amount_paid = models.FloatField()
    transaction_time = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=255)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=255, default='front-desk')
    modified_by = models.CharField(max_length=255, default='front-desk')
    is_deleted = models.BooleanField(default=False)

    # def __str__(self):
    #     return self.name

hotel_management/service/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import LaundryItemServicePrice, ClotheCategory, LaundryService, LaundryTranInfor, FBType, FBMeal, FBTranInfor

from booking.models import RentalInfor
from store.models import Room

from datetime import datetime

from basket.basket import LaudryBasket, FBMealBasket

def fb_meal_all(request):
    fb_types = FBType.objects.all()
    fb_meals = FBMeal.objects.all()

    return render(request, 'service/fb-meal-all.html', {'fb_types':fb_types, 'fb_meals':fb_meals})

def fb_meal_summary(request):
    fb_basket_obj = FBMealBasket(request)
    fb_basket = FBMealBasket(request).fb_basket.values()
    cost_before_tax = fb_basket_obj.get_cost_before_tax()
    total_tax = fb_basket_obj.get_total_tax()
    total_cost_with_tax = fb_basket_obj.get_total_cost_with_tax()
    return render(request, 'service/fb-summary.html', {'fb_basket':fb_basket, 'cost_before_tax':cost_before_tax, 'total_tax':total_tax, 'total_cost_with_tax':total_cost_with_tax})

# laundry
def food_drink_store(request):
    laundry_items = LaundryItemServicePrice.objects.all()
    clothe_types = ClotheCategory.objects.all()
    laundry_services = LaundryService.objects.all()
    return render(request, 'service/food-drink-sell.html', {'laundry_items':laundry_items, 'clothe_types':clothe_types, 'laundry_services':laundry_services})

# laundry
def food_drink_summary(request):
    laundry_basket_obj = LaudryBasket(request)
    laundry_basket = LaudryBasket(request).laundry_basket.values()
    cost_before_tax = laundry_basket_obj.get_cost_before_tax()
    total_tax = laundry_basket_obj.get_total_tax()
    total_cost_with_tax = laundry_basket_obj.get_total_cost_with_tax()

    return render(request, 'service/food-drink-summary.html', {'laundry_basket':laundry_basket, 'cost_before_tax':cost_before_tax, 'total_tax':total_tax, 'total_cost_with_tax':total_cost_with_tax})

def update_laundry_tran_db(request):
    laundry_basket = LaudryBasket(request)
    if request.POST.get('action') == 'post':
        roomCode = request.POST.get('roomName')
    
    # today_date = datetime.now()
    # today_date_str = today_date.strftime("%Y-%m-%d")

    today_str = str(datetime.now().date())
    today = datetime.strptime(today_str, "%Y-%m-%d")

    # 108.90 rent amount total LotusB02
    # roomCode = 'LotusB02'

    room_obj = Room.rooms.get(room_code=roomCode)

    rental_tran_objs = RentalInfor.objects.filter(room_id=room_obj, rental_date=today)
    rental_tran_obj = rental_tran_objs.first()
    total_cost = rental_tran_obj.rent_amount_total

    cost_before_tax = laundry_basket.get_cost_before_tax()
    tax = laundry_basket.get_total_tax()
    cost_with_tax = laundry_basket.get_total_cost_with_tax()

    laundry_tran_row = LaundryTranInfor.objects.create(
        rental_id = rental_tran_obj,
        room_id = room_obj,
        amount_paid = cost_before_tax,
        amount_tax = tax,
        total_amount_paid = cost_with_tax
    )
    response = JsonResponse({'name': "Pham Van Thai"})
    request.session['laundry'].clear()
    request.session.modified = True
    return response

def update_fb_tran_db(request):
    fb_basket = FBMealBasket(request)

    if request.POST.get('action') == 'post':
        roomCode = request.POST.get('roomName')

    # roomCode = 'LotusB02'

    today_str = str(datetime.now().date())
    today = datetime.strptime(today_str, "%Y-%m-%d")

    room_obj = Room.rooms.get(room_code=roomCode)
    rental_tran_objs = RentalInfor.objects.filter(room_id=room_obj, rental_date=today)
    rental_tran_obj = rental_tran_objs.first()

    cost_before_tax = fb_basket.get_cost_before_tax()
    tax = fb_basket.get_total_tax()
    cost_with_tax = fb_basket.get_total_cost_with_tax()

    fb_tran_row = FBTranInfor.objects.create(
        rental_id = rental_tran_obj,
        room_id = room_obj,
        amount_paid = cost_before_tax,
        amount_tax = tax,
        total_amount_paid = cost_with_tax
    )

    response = JsonResponse({'name': "Pham Van Thai"})
    request.session['fb_meal'].clear()
    request.session.modified = True
    return response

hotel_management/templates/service/fb-meal-all.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    
    <style>
        .container {
    padding-top: 100px;
    padding-bottom: 100px;
}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Lotus</a>
          <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Danh mục</a>
                    <ul class="dropdown-menu">
                    {% for fb_type in fb_types %}
                      <li><a class="dropdown-item" href="#">{{fb_type}}</a></li>
                    {% endfor %}
                      <!-- <li><a class="dropdown-item" href="#">Combo</a></li> -->
                    </ul>
                  </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">Đăng nhập</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'service:fb_meal_summary' %}" style="color: orangered;"><strong>Thanh toán</strong></a>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Switch account</a>
              </li> -->
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn" type="submit" style="border-color: orange;"><span style="color: orange;">Search</span></button>
            </form>
          </div>
        </div>
      </nav>

    <div class="container">
        <!-- <h1>Phạm Văn Thái</h1>
        <h1>Phạm Văn Thái</h1>
        <h1>Phạm Văn Thái</h1>
        <h1>Phạm Văn Thái</h1>
        <h1>Phạm Văn Thái</h1> -->
    

      <div class="row g-4">
        {% for fb_meal in fb_meals %}
        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="room-item shadow rounded overflow-hidden">
                <div class="position-relative">
                    <img class="img-fluid" src="{{ fb_meal.image.url }}" alt="">
                    <small class="position-absolute start-0 top-100 translate-middle-y  text-white rounded py-1 px-3 ms-4" style="background-color: orange;">$<span id="fb_item_price_{{fb_meal.id}}">{{fb_meal.cost}}</span></small>
                </div>
                <div class="p-4 mt-2">
                    <div class="d-flex justify-content-between mb-3">
                        <a href="#" style="color: black;"><h5 class="mb-0">{{fb_meal.name}}
                        </h5></a>
                        <div class="ps-2">
                            <small class="fa fa-star text-primary"></small>
                            <small class="fa fa-star text-primary"></small>
                            <small class="fa fa-star text-primary"></small>
                            <small class="fa fa-star text-primary"></small>
                            <small class="fa fa-star text-primary"></small>
                        </div>
                    </div>
                    <!-- <div class="d-flex mb-3">
                        <small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>{{room.bed_qty}} Bed</small>
                        <small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>{{room.bath_qty}} Bath</small>
                        <small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
                    </div> -->
                    <p class="text-body mb-3">{{fb_meal.description|slice:":100" }}...</p>
                    <div class="d-flex justify-content-end row">

                        <form action="/action_page.php" class="col-7">
                            <label for="fb_qty_{{fb_meal.id}}">Số lượng (cái/kg):</label>
                            <select name="laundry_qty" id="fb_qty_{{fb_meal.id}}">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                            </select>
                        </form>
                        
                        <a class="btn btn-sm btn-dark rounded py-2 px-4 col fb-add-button" href="" value="{{fb_meal.id}}">Thêm</a>
                        
                        
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script>
        $(document).on('click', '.fb-add-button', function (e) {
        e.preventDefault();
        // alert("Đã thêm vào giỏ hàng");
        var laundryItemID = $(this).attr('value');  // Lấy giá trị của thuộc tính 'value'
        var laundryString = "#fb_item_price_"+laundryItemID;
        var qtyString = '#fb_qty_'+laundryItemID+ ' option:selected';
        // var price = document.getElementById(laundryString.toString()).innerHTML;
        console.log(laundryString);
        console.log(qtyString);
        
        var price = $(laundryString).text();
        var itemqty = $(qtyString).text();

        console.log(itemqty);
        console.log(price);

        $.ajax({
            type: 'POST',
            url: '{% url "basket:fb_meal_basket_add" %}',
            data: {
                fbItemID: laundryItemID,
                itemqty: itemqty,
                price: price,
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
            //    document.getElementById("basket-qty").innerHTML = json.qty;
            console.log("Phạm Văn Thái")
            },
            error: function (xhr, errmsg, err) {}
        });
    })
    </script>

  </body>
</html>

hotel_management/templates/service/food-drink-sell.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    
    <style>
        .container {
    padding-top: 100px;
    padding-bottom: 100px;
}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Lotus</a>
          <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Danh mục</a>
                    <ul class="dropdown-menu">
                    {% for clothe_type in clothe_types %}
                      <li><a class="dropdown-item" href="#">{{clothe_type}}</a></li>
                    {% endfor %}
                    {% for laundry_service in laundry_services %}
                      <li><a class="dropdown-item" href="#">{{laundry_service}}</a></li>
                    {% endfor %}
                      <!-- <li><a class="dropdown-item" href="#">Combo</a></li> -->
                    </ul>
                  </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">Đăng nhập</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'service:food_drink_summary' %}" style="color: orangered;"><strong>Thanh toán</strong></a>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Switch account</a>
              </li> -->
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn" type="submit" style="border-color: orange;"><span style="color: orange;">Search</span></button>
            </form>
          </div>
        </div>
      </nav>

    <div class="container">
        <!-- <h1>Phạm Văn Thái</h1>
        <h1>Phạm Văn Thái</h1>
        <h1>Phạm Văn Thái</h1>
        <h1>Phạm Văn Thái</h1>
        <h1>Phạm Văn Thái</h1> -->
    

      <div class="row g-4">
        {% for laundry_item in laundry_items %}
        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="room-item shadow rounded overflow-hidden">
                <div class="position-relative">
                    <img class="img-fluid" src="{{ laundry_item.image.url }}" alt="">
                    <small class="position-absolute start-0 top-100 translate-middle-y  text-white rounded py-1 px-3 ms-4" style="background-color: orange;">$<span id="laundry_item_price_{{laundry_item.id}}">{{laundry_item.cost}}</span></small>
                </div>
                <div class="p-4 mt-2">
                    <div class="d-flex justify-content-between mb-3">
                        <a href="#" style="color: black;"><h5 class="mb-0">{{laundry_item.name}}
                        </h5></a>
                        <div class="ps-2">
                            <small class="fa fa-star text-primary"></small>
                            <small class="fa fa-star text-primary"></small>
                            <small class="fa fa-star text-primary"></small>
                            <small class="fa fa-star text-primary"></small>
                            <small class="fa fa-star text-primary"></small>
                        </div>
                    </div>
                    <!-- <div class="d-flex mb-3">
                        <small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>{{room.bed_qty}} Bed</small>
                        <small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>{{room.bath_qty}} Bath</small>
                        <small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
                    </div> -->
                    <p class="text-body mb-3">{{laundry_item.description|slice:":100" }}...</p>
                    <div class="d-flex justify-content-end row">

                        <form action="/action_page.php" class="col-7">
                            <label for="laundry_qty_{{laundry_item.id}}">Số lượng (cái/kg):</label>
                            <select name="laundry_qty" id="laundry_qty_{{laundry_item.id}}">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                            </select>
                        </form>
                        
                        <a class="btn btn-sm btn-dark rounded py-2 px-4 col laundy-add-button" href="" value="{{laundry_item.id}}">Thêm</a>
                        
                        
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script>
        $(document).on('click', '.laundy-add-button', function (e) {
        e.preventDefault();
        var laundryItemID = $(this).attr('value');  // Lấy giá trị của thuộc tính 'value'
        var laundryString = "#laundry_item_price_"+laundryItemID;
        var qtyString = '#laundry_qty_'+laundryItemID+ ' option:selected';
        // var price = document.getElementById(laundryString.toString()).innerHTML;
        console.log(laundryString);
        console.log(qtyString);
        
        var price = $(laundryString).text();
        var itemqty = $(qtyString).text();

        console.log(itemqty);
        console.log(price);

        $.ajax({
            type: 'POST',
            url: '{% url "basket:laundry_basket_add" %}',
            data: {
                laundryItemID: laundryItemID,
                itemqty: itemqty,
                price: price,
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
            //    document.getElementById("basket-qty").innerHTML = json.qty;
            console.log("Phạm Văn Thái")
            },
            error: function (xhr, errmsg, err) {}
        });
    })
    </script>

  </body>
</html>