hotel_management/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.reservation_detail, name='reservation_detail'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('laundry_basket_add/', views.laundry_basket_add, name='laundry_basket_add'),
    path('fb_meal_basket_add/', views.fb_meal_basket_add, name='fb_meal_basket_add'),
    # path('delete/', views.basket_delete, name='basket_delete'),
    # path('update/', views.basket_update, name='basket_update'),
]

hotel_management/hotel_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('account/', include('human_resource.urls', namespace='human_resource')),
    path('service/', include('service.urls', namespace='service')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel_management/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('room_all/', views.room_all, name="room_all"),
    path('<slug:slug>', views.room_detail, name="room_detail"),

    # path('reservation_detail/', views.reservation_detail, name="reservation_detail"),
    path('service/', views.service, name="service"),
    path('service/service_meal', views.service_meal, name="service_meal"),
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('team/', views.team, name="team"),
    # path('booking/', views.booking, name="booking"),
    path('contact/', views.contact, name="contact"),
    path('testimonial/', views.testimonial, name="testimonial"),
]

hotel_management/templates/room/room_all.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Room All{% endblock %}
{% block content %}

<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title text-center text-primary text-uppercase">Tất cả phòng</h6>
            <h1 class="mb-5">Khám phá <span class="text-primary text-uppercase">Phòng</span></h1>
        </div>
        <div class="row g-4">
            {% for room in rooms %}
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="room-item shadow rounded overflow-hidden">
                    <div class="position-relative">
                        <img class="img-fluid" src="{{ room.image.url }}" alt="">
                        <small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">${{room.price}}/Đêm</small>
                    </div>
                    <div class="p-4 mt-2">
                        <div class="d-flex justify-content-between mb-3">
                            <a href="{{ room.get_absolute_url }}"><h5 class="mb-0">{{room.room_code}}
                            </h5></a>
                            <div class="ps-2">
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                            </div>
                        </div>
                        <div class="d-flex mb-3">
                            <small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>{{room.bed_qty}} Giường</small>
                            <small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>{{room.bath_qty}} Bồn tắm</small>
                            <small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
                        </div>
                        <p class="text-body mb-3">{{room.description|slice:":100" }}...</p>
                        <div class="d-flex justify-content-end row">

                            <form action="/action_page.php" class="col-7">
                                <label for="cars">Số lượng phòng:</label>
                                <select name="cars" id="cars">
                                    <option value="1">1</option>
                                </select>
                            </form>
                            <a class="btn btn-sm btn-dark rounded py-2 px-4 col" href="">Thêm</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

hotel_management/templates/room/room_all_search.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Room All{% endblock %}
{% block content %}

<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title text-center text-primary text-uppercase">Our Rooms</h6>
            <h1 class="mb-5">Explore Our <span class="text-primary text-uppercase">Rooms</span></h1>
        </div>
        <div class="row g-4">
            {% for room in rooms_query %}
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="room-item shadow rounded overflow-hidden">
                    <div class="position-relative">
                        <img class="img-fluid" src="{{ room.image.url }}" alt="">
                        <small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">${{room.price}}/Night</small>
                    </div>
                    <div class="p-4 mt-2">
                        <div class="d-flex justify-content-between mb-3">
                            <a href="{{ room.get_absolute_url }}"><h5 class="mb-0">{{room.room_code}}
                            </h5></a>
                            <div class="ps-2">
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                            </div>
                        </div>
                        <div class="d-flex mb-3">
                            <small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>{{room.bed_qty}} Bed</small>
                            <small class="border-end me-3 pe-3"><i class="fa fa-bath text-primary me-2"></i>{{room.bath_qty}} Bath</small>
                            <small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
                        </div>
                        <p class="text-body mb-3">{{room.description|slice:":100" }}...</p>
                        <div class="d-flex justify-content-end row">

                            <form action="/action_page.php" class="col-7">
                                <label for="cars">Số lượng phòng:</label>
                                <select name="cars" id="cars">
                                    <option value="1">1</option>
                                </select>
                            </form>
                            <a class="btn btn-sm btn-dark rounded py-2 px-4 col" href="">Add</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

hotel_management/templates/room/room_detail.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Room All{% endblock %}
{% block content %}

<div class="container-xxl py-5">
    <div class="container">
        <div class="single-product">
            <div class="row">
                <div class="col-6">
                    <div class="product-image">
                        <div class="product-image-main">
                            <img src="{{ room.image.url }}" alt="" id="product-main-image">
                        </div>
                        <div class="product-image-slider">
                            <img src="{{ room.image.url }}" alt=""  class="image-list">
                            <img src="{{ room.image1.url }}" alt=""  class="image-list">
                            <img src="{{ room.image2.url }}" alt=""  class="image-list">
                            <img src="{{ room.image3.url }}" alt=""  class="image-list">
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    

                    <div class="product">
                        <div class="product-title">
                            <h2>{{room.room_code}}-{{room_type.name}}</h2>
                        </div>
                        <!-- <div class="product-rating">
                            <span><i class="bx bxs-star"></i></span>
                            <span><i class="bx bxs-star"></i></span>
                            <span><i class="bx bxs-star"></i></span>
                            <span><i class="bx bxs-star"></i></span>
                            <span><i class="bx bxs-star"></i></span>
                            <span class="review">(47 Nhận xét)</span>
                        </div> -->
                        <div class="product-price">
                            <span class="offer-price">${{room.price}}</span>
                            <!-- <span class="sale-price">$129.00</span> -->
                        </div>

                        <div class="product-details">
                            <h3>Mô tả</h3>
                            <p>{{room.description}}</p>
                        </div>
                        
                        <div>
                        
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="black" class="bi bi-person-fill-add" viewBox="0 0 16 16">
                                <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                <path d="M2 13c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4"/>
                              </svg>
                            <div>
                            {{room_type.bed_adult}} người lớn, có thể thêm người.
                            <br>
                            Khách 0 - 5 tuổi được ở miễn phí.
                            <br>
                            Tối đa {{room_type.max_adult}} người lớn , {{room_type.max_child}} trẻ em ở ghép.
                        </div>
                            
                        </div>

                        <div>
                            <a href="{% url 'store:service_meal' %}">Hay đăng ký cùng vụ ăn uống...</a>
                        </div>
                        <div class="row g-2">
                            <div>
                                <form action="/action_page.php">
                                    <label for="mealcode_select">Đặt dịch vụ ăn uống:</label>
                                    <select name="cars" id="mealcode_select">
                                        <option value="volvo">Không sử dụng</option>
                                        {% for meal_code in meal_codes %}
                                        <option value="{{meal_code.meal_code}}">{{meal_code.meal_code}}</option>
                                        {% endfor %}
                                    </select>
                                  </form>
                            </div>
                            <div class="row">
                            <div class="col-4">
                                <form action="/action_page.php">
                                    <label for="adult_select">Người lớn:</label>
                                    <select id="adult_select">
                                        {% for i in adult_selected_list %}
                                        <option value="{{i}}">{{i}}</option>
                                        {% endfor %}
                                    </select>
                                  </form>
                            </div>
                            <div class="col">
                                <form action="/action_page.php">
                                    <label for="child_select">Trẻ em:   </label>
                                    <select id="child_select">
                                        {% for i in child_selected_list %}
                                        <option value="{{i}}">{{i}}</option>
                                        {% endfor %}
                                    </select>
                                  </form>
                            </div>
                        </div>
                        </div>
                        
                        
                        <span class="divider"></span>

                        <div class="product-btn-group">
                            <a href="{% url 'store:room_all' %}"><div class="button buy-now"><i class='bx bxs-zap' ></i> Quay lại</div></a>
                            <div id="add-button" value="{{room.id}}" class="button add-cart"><i class='bx bxs-cart' ></i> Thêm</div>
                            <!-- <div class="button heart"><i class='bx bxs-heart' ></i> Add to Wishlist</div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        var roomId = $(this).attr('value');  // Lấy giá trị của thuộc tính 'value'
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                roomid: roomId,
                roomqty: '1',
                mealcode: $('#mealcode_select option:selected').text(),
                adultqty: $('#adult_select option:selected').text(),
                childqty: $('#child_select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty;
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}