hotel_management/hotel_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('booking/', include('booking.urls', namespace='booking')),
    path('account/', include('human_resource.urls', namespace='human_resource')),
    path('service/', include('service.urls', namespace='service')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel_management/human_resource/urls.py
from django.urls import path

from . import views

app_name = 'human_resource'

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutUser, name='logout'),
]

hotel_management/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('room_all/', views.room_all, name="room_all"),
    path('<slug:slug>', views.room_detail, name="room_detail"),

    # path('reservation_detail/', views.reservation_detail, name="reservation_detail"),
    path('service/', views.service, name="service"),
    path('service/service_meal', views.service_meal, name="service_meal"),
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('team/', views.team, name="team"),
    # path('booking/', views.booking, name="booking"),
    path('contact/', views.contact, name="contact"),
    path('testimonial/', views.testimonial, name="testimonial"),
]

hotel_management/templates/login_register/login.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.css" rel="stylesheet">
    <style>
        .gradient-custom-2 {
            /* fallback for old browsers */
            background: #fccb90;

            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);

            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
        }

        /* @media (min-width: 768px) {
            .gradient-form {
                height: 100vh !important;
            }
        } */

        @media (min-width: 769px) {
            .gradient-custom-2 {
                border-top-right-radius: .3rem;
                border-bottom-right-radius: .3rem;
            }
        }
    </style>
</head>

<body>
    <section class="h-100 gradient-form" style="background-color: #eee;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 mx-md-4">

                                    <div class="text-center">
                                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                                            style="width: 185px;" alt="logo">
                                        <h4 class="mt-1 mb-5 pb-1">Chúng tôi là khách sạn Lotus</h4>
                                    </div>

                                    <form method="POST">
                                        {% csrf_token %}
                                        <p>Vui lòng dùng tài khoản đăng nhập</p>

                                        <div data-mdb-input-init class="form-outline mb-4">
                                            <input type="email" id="form2Example11" class="form-control"
                                                placeholder="Phone number or email address" name="email" />
                                            <label class="form-label" for="form2Example11">Email</label>
                                        </div>

                                        <div data-mdb-input-init class="form-outline mb-4">
                                            <input type="password" id="form2Example22" class="form-control" name="password"/>
                                            <label class="form-label" for="form2Example22" placeholder="Password">Mật khẩu</label>
                                        </div>

                                        <div class="text-center pt-1 mb-5 pb-1">
                                            <button data-mdb-button-init data-mdb-ripple-init
                                                class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3"
                                                type="submit">Đăng nhập</button>
                                            <a class="text-muted" href="#!">Quên mật khẩu?</a>
                                        </div>

                                        <div class="d-flex align-items-center justify-content-center pb-4">
                                            <p class="mb-0 me-2">Chưa có tài khoản?</p>
                                            <button type="button" data-mdb-button-init data-mdb-ripple-init
                                                class="btn btn-outline-danger" onclick="window.location.href='{% url 'human_resource:register' %}'">Tạo mới</button>
                                        </div>

                                    </form>

                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                    <h4 class="mb-4">Chúng tôi còn hơn là một khách sạn</h4>
                                    <p class="small mb-0">Chúc bạn có một trải nghiệm thật tuyệt vời khi đến với khách sạn Lotus.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

hotel_management/templates/login_register/register.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.css" rel="stylesheet">
    <style>
        .gradient-custom-2 {
            /* fallback for old browsers */
            background: #fccb90;

            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);

            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
        }

        /* @media (min-width: 768px) {
            .gradient-form {
                height: 100vh !important;
            }
        } */

        @media (min-width: 769px) {
            .gradient-custom-2 {
                border-top-right-radius: .3rem;
                border-bottom-right-radius: .3rem;
            }
        }
    </style>
    <style>
        .form-group {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }
    
        .form-group label {
            margin-bottom: 0.5rem;
        }
    
        .form-group input, .form-group select, .form-group textarea {
            width: 100%;
        }
    </style>
    
</head>

<body>
    <section class="h-100 gradient-form" style="background-color: #eee;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 mx-md-4">

                                    <div class="text-center">
                                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                                            style="width: 185px;" alt="logo">
                                        <h4 class="mt-1 mb-5 pb-1">Chúng tôi là khách sạn Lotus</h4>
                                    </div>

                                    <form method="POST">
                                        {% csrf_token %}
                                        <p>Đăng ký tài khoản</p>
                                    
                                        <div data-mdb-input-init class="form-outline mb-4 form-group">
                                            <label class="form-label" for="name">Họ và tên</label>
                                            {{ form.name }}
                                        </div>
                                    
                                        <div data-mdb-input-init class="form-outline mb-4 form-group">
                                            <label class="form-label" for="username">Tên người dùng</label>
                                            {{ form.username }}
                                        </div>
                                    
                                        <div data-mdb-input-init class="form-outline mb-4 form-group">
                                            <label class="form-label" for="email">Email</label>
                                            {{ form.email }}
                                        </div>
                                    
                                        <div data-mdb-input-init class="form-outline mb-4 form-group">
                                            <label class="form-label" for="password1">Mật khẩu</label>
                                            {{ form.password1 }}
                                        </div>
                                    
                                        <div data-mdb-input-init class="form-outline mb-4 form-group">
                                            <label class="form-label" for="password2">Nhập lại mật khẩu</label>
                                            {{ form.password2 }}
                                        </div>
                                    
                                        <div class="text-center pt-1 mb-5 pb-1">
                                            <button data-mdb-button-init data-mdb-ripple-init
                                                    class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3"
                                                    type="submit">Đăng ký</button>
                                            <a class="text-muted" href="#!">Quên mật khẩu?</a>
                                        </div>
                                    
                                        <div class="d-flex align-items-center justify-content-center pb-4">
                                            <p class="mb-0 me-2">Đã có tài khoản?</p>
                                            <a href="{% url 'human_resource:login' %}" class="btn btn--link">Đăng nhập</a>
                                        </div>
                                    </form>
                                    

                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                    <h4 class="mb-4">Chúng tôi còn hơn là một khách sạn</h4>
                                    <p class="small mb-0">Chúc bạn có một trải nghiệm thật tuyệt vời khi đến với khách sạn Lotus.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>